version: "3.8"

services:
  app:
    build: .
    image: organization-service
    container_name: organization-service-app-1
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=metrics
      - SPRING_R2DBC_URL=r2dbc:postgresql://db:5432/organization_service
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=changemeinprod!
      - SPRING_FLYWAY_URL=jdbc:postgresql://db:5432/organization_service
      - SPRING_FLYWAY_USER=postgres
      - SPRING_FLYWAY_PASSWORD=changemeinprod!
      - KAFKA_BOOTSTRAP_SERVERS=kafka-1:9092
      - LOGGING_CONFIG=classpath:log4j2.xml
      - LOGGING_FILE_PATH=/app/logs
    volumes:
      - org-service-logs:/app/logs
    depends_on:
      - db
    networks:
      - default
      - kafka-network

  db:
    image: postgres:15
    container_name: organization-service-db-1
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changemeinprod!
      - POSTGRES_DB=organization_service
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - default

networks:
  default:
    name: organization-service-network
  kafka-network:
    external: true

volumes:
  pg_data:
    driver: local
  org-service-logs:
    driver: local
