apiVersion: v1
kind: Service
metadata:
  name: orgservice
spec:
  selector:
    app: orgservice
  ports:
    - protocol: TCP
#      he port on which the service is exposed inside the cluster.
      port: 80
#      the port on which the application is running inside the pod.
      targetPort: 8080
#      the port on which the service is exposed on each node in the cluster.
      nodePort: 30007
  type: NodePort